services:
  postgres:
    image: postgres:16-alpine
    container_name: orderflow-postgres
    environment:
      POSTGRES_USER: orderflow_admin
      POSTGRES_PASSWORD: orderflow_admin
      POSTGRES_DB: postgres
      ORDER_DB_PASSWORD: order_service_password
      PROCESSOR_DB_PASSWORD: processor_service_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orderflow_admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:latest
    container_name: orderflow-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  order:
    build:
      context: ../order
    container_name: orderflow-order
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/orderflow_order
      DB_USERNAME: order_service
      DB_PASSWORD: order_service_password
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  processor:
    build:
      context: ../processor
    container_name: orderflow-processor
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/orderflow_processor
      DB_USERNAME: processor_service
      DB_PASSWORD: processor_service_password
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  ws-adapter:
    build:
      context: ../ws-adapter
    container_name: orderflow-ws-adapter
    ports:
      - "8082:8080"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  frontend:
    build:
      context: ../frontend
    container_name: orderflow-frontend
    ports:
      - "3000:3000"
    depends_on:
      - order
      - ws-adapter

volumes:
  postgres_data:
